# Generated by Django 6.0 on 2025-12-18 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_companies_member_memberships_and_more'),
        ('videos_app', '0003_alter_video_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.AddField(
            model_name='video',
            name='member',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploded_videos', to='companies.memberships'),
        ),
        migrations.AlterField(
            model_name='video',
            name='admin',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_videos', to='companies.memberships'),
        ),
    ]
