# Generated by Django 6.0 on 2025-12-27 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_companies_member_memberships_and_more'),
        ('videos_app', '0004_remove_video_user_video_member_alter_video_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='admin',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_videos', to='companies.memberships'),
        ),
    ]
