# Generated by Django 6.0 on 2025-12-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='systemAdmin',
            new_name='system_admin',
        ),
    ]
