# Generated by Django 6.0 on 2025-12-12 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('balance', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CompaniesMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(choices=[('User', 'Пользователь'), ('Admin', 'Админ'), ('Super Admin', 'Супер Админ')], default='User', max_length=20)),
                ('status', models.TextField(choices=[('Active', 'Активный'), ('Banned', 'Забанен')], default='Active', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mebership', to='companies.companies')),
            ],
        ),
    ]
