# Generated by Django 6.0 on 2026-01-30 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('balance', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Мои компании',
                'verbose_name_plural': 'Мои компании',
            },
        ),
        migrations.CreateModel(
            name='Memberships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(choices=[('User', 'Пользователь'), ('Admin', 'Админ'), ('Super Admin', 'Супер Админ')], default='User', max_length=20)),
                ('status', models.TextField(choices=[('Active', 'Активный'), ('Banned', 'Забанен')], default='Active', max_length=20)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.companies')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мои пользовтели',
                'verbose_name_plural': 'Пользователи моих компаний',
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.AddField(
            model_name='companies',
            name='members',
            field=models.ManyToManyField(related_name='companies', through='companies.Memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('solution', models.IntegerField(choices=[(0, 'Отклонено'), (1, 'Принято'), (2, 'Ожидает')], default=2)),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_videos', to='companies.memberships')),
                ('member', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploded_videos', to='companies.memberships')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
