# Generated by Django 6.0 on 2026-02-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberships',
            name='status',
        ),
        migrations.AddField(
            model_name='memberships',
            name='is_active',
            field=models.TextField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
