# Generated by Django 6.0 on 2026-02-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_memberships_status_memberships_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberships',
            name='is_active',
            field=models.BooleanField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='memberships',
            name='role',
            field=models.TextField(choices=[('user', 'Пользователь'), ('admin', 'Админ'), ('superadmin', 'Супер Админ')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='solution',
            field=models.IntegerField(choices=[(0, 'отклонено'), (1, 'принято'), (2, 'ожидает')], default=2),
        ),
    ]
