# Generated by Django 6.0 on 2025-12-12 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companiesmembers_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='member',
            field=models.ManyToManyField(related_name='companiesMembers', through='companies.CompaniesMembers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companiesmembers',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='companies.companies'),
        ),
        migrations.AlterField(
            model_name='companiesmembers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
