# Generated by Django 6.0 on 2025-12-18 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_companies_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='member',
            field=models.ManyToManyField(related_name='companie', through='companies.CompaniesMembers', to=settings.AUTH_USER_MODEL),
        ),
    ]
