# Generated by Django 6.0 on 2025-12-18 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_companies_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='member',
        ),
        migrations.CreateModel(
            name='Memberships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(choices=[('User', 'Пользователь'), ('Admin', 'Админ'), ('Super Admin', 'Супер Админ')], default='User', max_length=20)),
                ('status', models.TextField(choices=[('Active', 'Активный'), ('Banned', 'Забанен')], default='Active', max_length=20)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.companies')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.AddField(
            model_name='companies',
            name='members',
            field=models.ManyToManyField(related_name='companies', through='companies.Memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CompaniesMembers',
        ),
    ]
