# Generated by Django 6.0 on 2025-12-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_companies_member_memberships_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name': 'Мои компании', 'verbose_name_plural': 'Мои компании'},
        ),
        migrations.AlterModelOptions(
            name='memberships',
            options={'verbose_name': 'Мои пользовтели', 'verbose_name_plural': 'Пользователи моих компаний'},
        ),
    ]
